$primary_paletteKeyColor = 308197
$secondary_paletteKeyColor = 647b83
$tertiary_paletteKeyColor = 717598
$neutral_paletteKeyColor = 72787a
$neutral_variant_paletteKeyColor = 70787c
$background = 0f1416
$onBackground = dee3e6
$surface = 0f1416
$surfaceDim = 0f1416
$surfaceBright = 343a3c
$surfaceContainerLowest = 090f11
$surfaceContainerLow = 171c1e
$surfaceContainer = 1b2023
$surfaceContainerHigh = 252b2d
$surfaceContainerHighest = 303638
$onSurface = dee3e6
$surfaceVariant = 40484b
$onSurfaceVariant = bfc8cc
$inverseSurface = dee3e6
$inverseOnSurface = 2c3133
$outline = 899296
$outlineVariant = 40484b
$shadow = 000000
$scrim = 000000
$surfaceTint = 86d1e9
$primary = 86d1e9
$onPrimary = 003642
$primaryContainer = 004e5f
$onPrimaryContainer = b2ebff
$inversePrimary = 00677d
$secondary = b3cad3
$onSecondary = 1d343b
$secondaryContainer = 344a52
$onSecondaryContainer = cee6f0
$tertiary = c1c4eb
$onTertiary = 2a2e4d
$tertiaryContainer = 8b8eb3
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = b2ebff
$primaryFixedDim = 86d1e9
$onPrimaryFixed = 001f27
$onPrimaryFixedVariant = 004e5f
$secondaryFixed = cee6f0
$secondaryFixedDim = b3cad3
$onSecondaryFixed = 061e25
$onSecondaryFixedVariant = 344a52
$tertiaryFixed = dfe0ff
$tertiaryFixedDim = c1c4eb
$onTertiaryFixed = 151937
$onTertiaryFixedVariant = 414465
$term0 = 343434
$term1 = 8383ff
$term2 = 3fe0e3
$term3 = 75fcdd
$term4 = 79b3c3
$term5 = 7aaee9
$term6 = 81d7e0
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 00f5fa
$term11 = c9fff3
$term12 = a4c7ce
$term13 = a2c0f7
$term14 = 87eaf4
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = c0e1ff
$mauve = 76c9fc
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d0f9f4
$green = 8beffa
$teal = a1ebfc
$sky = 98e7fe
$sapphire = 79d3f1
$blue = 68c8f0
$lavender = 92d5f9
$klink = 0093b7
$klinkSelection = 0093b7
$kvisited = 0089c2
$kvisitedSelection = 0089c3
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bbca
$kpositiveSelection = 00bbcb
$text = dee3e6
$subtext1 = bfc8cc
$subtext0 = 899296
$overlay2 = 777f83
$overlay1 = 646c6f
$overlay0 = 535a5d
$surface2 = 43494c
$surface1 = 32383b
$surface0 = 202628
$base = 0f1416
$mantle = 0f1416
$crust = 0e1315
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
